nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "tinyurl1:tinyurl1"
    - "tinyurl2:tinyurl2"
    - "tinyurl3:tinyurl3"

tinyurl1:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

tinyurl2:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

tinyurl3:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

cache:
  image: redis